### ISSUE TITLE
Use relative filepath for define_regions attribute of bmi_ilamb.yaml

### ISSUE THREAD

**Issue by mdpiper** [permamodel/bmi-ilamb#9]
The **wmt-permafrost** instance produced the following **bmi_ilamb.yaml**:

```yaml
config: ilamb.cfg
ilamb_root: /nas/data/ilamb
model_root: MODELS
build_dir: _build
define_regions: /data/web/htdocs/wmt/api/permafrost/files/uploads/133/above.txt
regions: ['global', 'above']
models: ['SiBCASA']
confrontations: 
```

The absolute path in the `define_regions` attribute is valid on the server, ***diluvium***, but certainly not on the executor, ***beach***. Consider restricting this attribute to a relative filepath.
